kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
  namespace: projectx89
rules:

- apiGroups: ["apps.openshift.io/v1"]
  resources: ["DeploymentConfig"]
  verbs: ["get", "list", "watch", "create", "update"]

- apiGroups: [""]
  resources: ["configmaps", "pods"]
  verbs: ["get", "list", "watch"]

- verbs:
    - get
  apiGroups:
    - ''
    - project.openshift.io
  resources:
    - projects