apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-projectx89-cicd
  namespace: projectx89
subjects:
  - kind: Group
    name: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd-role
