apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: po-projectx91-view
  namespace: projectx91
subjects:
- kind: Group
  name: po
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view